# Generated by Django 6.0.3 on 2026-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_elixservicecall_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='equipe',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
